### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by camilstaps** [camilstaps/ReverseBeaconClient#9]
From Android vitals:

```
java.lang.IllegalStateException: 
  at android.app.Fragment.getResources(Fragment.java:814)
  at nl.camilstaps.rbn.android.d$1.b(d.java:0)
  at nl.camilstaps.rbn.d.b(d.java:0)
  at nl.camilstaps.rbn.d$a.run(d.java:0)
  at java.lang.Thread.run(Thread.java:762)
```

**Comment by camilstaps** [comment]
No new crashes have been reported since 1.1.6.
